joelibaceta/hacktoberfest-training-2019

survey.csv
=> added entry in survey.csv

contributors.md, survey.csv
Great way to practice contributing and using  a pull request for the first time :)
=> Added my name to contributors and filled out survey

contributors.md, survey.csv
refs #2 Added my name and info to contributors.md and survey.csv
=> added my info for survery in contributors and survey files

contributors.md, survey.csv
Added name in contributors.md
Added  preferences in survey.csv
=> Added details and coding pref!

contributors.md, survey.csv
=> Hacktoberfest 2019

contributors.md, survey.csv
=> Updated survey

contributors.md, survey.csv
=> docs: Adding a contributor

contributors.md, survey.csv
=> added name and completed survey

contributors.md, survey.csv
As part of hacktoberfest issue #2 :)
=> Added details to contributors + survey

contributors.md, survey.csv
Added details to contributors.md and survey.csv
=> Added details

README.md, contributors.md, survey.csv
1. Added my name to CONTRIBUTERS.md
2. Added my details to SURVEY.csv
3. Changed the word survey.md to survey.csv to avoid confusions
=> Added my details to the survey

contributors.md, survey.csv
https://github.com/joelibaceta/hacktoberfest-2019/issues/2
=> Added data

contributors.md, survey.csv
connect to https://github.com/joelibaceta/hacktoberfest-2019/issues/2
=> Contributing to survey

contributors.md, survey.csv
Added new user entries, its a fun repository to contribute to
=> Added new entries

contributors.md, survey.csv
=> added myself

contributors.md, survey.csv
I have added my stats to your survey. csv file, as well as my name to the contributors. The merge shows that I am removing a name and adding it back, but i didnt change any whitespace. Cheers!
`timmay54`
=> Added tim mardesen to contributors.md & stats to survey

contributors.md, survey.csv
=> Updated contributors.md and survey.csv

contributors.md, survey.csv
=> make changers

contributors.md, survey.csv
=> Updating contributors.md and survey.csv (Be part of Hacktoberfest! #2)

contributors.md, survey.csv
Thank you for this repo, it is my first time participating in hacktoberfest
=> Contributed by Ricky Singh

survey.csv
[Be part of Hacktoberfest! #2](https://github.com/joelibaceta/hacktoberfest-training-2019/issues/2)
=> add infor to survey
